version: '3.7'

services:
    bisq-bitcoind:
        image: bisq/bitcoind:latest
        deploy:
            replicas: 1
            restart_policy:
                condition: any
        ports:
            - 8333:8333 # bitcoind port
        volumes:
            - ./bitcoind_data_dir:/root/.bitcoin
            - ./blocknotify.sh:/blocknotify.sh
        command:
            - -server=1
            - -listen=1
            - -discover=1
            - -txindex=1
            - -dbcache=1337
            - -maxconnections=1337
            - -peerbloomfilters=1
            - -rpcallowip=127.0.0.1
            - -rpcallowip=172.0.0.1/8 # Docker IP range
            - -rpcuser=bisq
            - -rpcpassword=bisq
            - -blocknotify=/blocknotify.sh %s
            - -bind=0.0.0.0:8332
            - -rpcbind=0.0.0.0:8332

    bisq-seednode:
        image: bisq/seednode:latest
        environment:
            - JDK_JAVA_OPTIONS=-Xms4096M -Xmx4096M -XX:+ExitOnOutOfMemoryError
        configs:
            - bisq_seednode_config
        deploy:
            replicas: 1
            restart_policy:
                condition: any
        ports:
            - 8000:8000 # bisq node port
        volumes:
            - bisq_seednode_data:/bisq/bisq-seednode
        command:
            - --configFile=/bisq_seednode_config

    bisq-tor:
        image: bisq/tor:latest
        deploy:
            replicas: 1
            restart_policy:
                condition: any
        volumes:
            - tor_data:/root/.tor
        command: [ "--allow-missing-torrc",
                   "--SOCKSPort", "0.0.0.0:9050",
                   "--ControlPort", "0.0.0.0:9051",
                   "--HashedControlPassword", "16:ED08CEBE4E91EA126089506E2880119E20A39054754D3916EAFF774046", # password: bisq
                   "--Log", "notice",
                   "--SafeSocks", "0",
                   "--HiddenServiceStatistics", "0",
                   "--AvoidDiskWrites", "1" ]

configs:
    bisq_seednode_config:
        file: ./seednode_config

volumes:
    bisq_seednode_data:
    tor_data:
